### PR TITLE
Unboxedness

### PR DESCRIPTION
**Pull request by treeowl**
OK, against the right branch now.

### CODE REVIEW

**Comment by treeowl** [comment]
I would definitely suggest checking your benchmarks to make sure this isn't worse than what you were doing before, just in case there's something brittle. And if we *can* reduce the unboxed thing to `INLINABLE` without reducing perf that would certainly be nice.

**Comment by oberblastmeister** [comment]
The benchmarks stay the same

**Comment by treeowl** [comment]
Awesome. You want to check what happens using `intersectionWithKey#` for the strict version?

**Comment by oberblastmeister** [comment]
Yeah I will

**Pull request merged**
